version: '2'
services:
 openrefine:
   hostname: open.refine
   build: ./or/.
   #image: granthbr/open-refine
   volumes:
    - or-data:/mnt/refine 
   ports:
    - "3333:3333"
volumes:
 or-data:
   external: true

